[package]
name = "wifipass-windows"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.56"
features = [
    "Data_Xml_Dom",
    "Foundation_Collections",
    "Win32_Foundation",
    "Win32_NetworkManagement_WiFi",
]
